export const DEFAULT_BADGES = [
  {
    name: "First Steps",
    slug: "first-course",
    description: "Completed your first course on DeenBridge",
    icon: "badge_first_course.png",
    category: "milestone",
    criteriaType: "courses_completed",
    threshold: 1,
  },
  {
    name: "Dedicated Learner",
    slug: "5-courses",
    description: "Successfully completed 5 courses",
    icon: "badge_5_courses.png",
    category: "milestone",
    criteriaType: "courses_completed",
    threshold: 5,
  },
  {
    name: "Knowledge Seeker",
    slug: "10-courses",
    description: "Successfully completed 10 courses",
    icon: "badge_10_courses.png",
    category: "milestone",
    criteriaType: "courses_completed",
    threshold: 10,
  },
  {
    name: "Master Scholar",
    slug: "20-courses",
    description: "Achieved mastery by completing 20 courses",
    icon: "badge_20_courses.png",
    category: "milestone",
    criteriaType: "courses_completed",
    threshold: 20,
  },
  {
    name: "Category Expert",
    slug: "category-expert",
    description: "Completed 3 or more courses within a single topic category",
    icon: "badge_category_expert.png",
    category: "achievement",
    criteriaType: "category_completed",
    threshold: 3,
  },
];
